### PR TITLE
News fixes

### PR DESCRIPTION
**Pull request by PascalSchumacher**
I did something wrong when rebasing, because this should be just one commit: 902f4c59221523fe8fdc290143a5aad6f0c8373f 

I guess you are going to cherry-pick anyway, so it does not matter?

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@joel-costigliola I know you have a lot to do, but what about cherry-picking 902f4c5?

**Comment by joel-costigliola** [comment]
sure, don't hesitate to remind me of stuff, sometimes it just slips out of my mind (other times is because I'm busy). BTW I'll be off next week for two weeks ... holidays :-)

**Comment by joel-costigliola** [comment]
Integrated, thanks.

@PascalSchumacher just to let you know, when you want to update the documentation, you need to change the template files , generate the site and commit the generated files as explained here http://joel-costigliola.github.io/assertj/assertj-help.html.
No big deal if you don't as I will do it anyway but it's good to know what the right thing is.

**Comment by PascalSchumacher** [comment]
Thanks for merging. :smile: 

I will generate the site next time.

Enjoy your holidays! :smile:

**Pull request closed without merging**
