### PR TITLE
Present exception testing with Lambda.

### PR DESCRIPTION
**Pull request by stefanbirkner**
Testing assertions could be easily done with Java 8 Lambdas. This pull request presents a solution that uses the Fishbowl library.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
We already have implemented exceptions assertions using lambda (in java-8 branch), you can have a look at this [test](https://github.com/joel-costigliola/assertj-core/blob/b82b7728b50abf7bac740533f500e85f79272432/src/test/java/org/assertj/core/api/throwable/ThrowableAssert_built_from_lambda_Test.java).

Anyway, AssertJ policy is not to rely on third party library.

**Comment by stefanbirkner** [comment]
Nice coincidence that we have chosen the same wording :-) I didn't know of the java-8 branch.

**Comment by joel-costigliola** [comment]
Nice indeed ! :) 
We had a long debate to get a good wording and your suggestion makes me think we choose this one right.

**Comment by joel-costigliola** [comment]
And if you want to play with assertj-core for java 8, I have released a milestone to get some feedback.
It's available here : http://search.maven.org/#artifactdetails|org.assertj|assertj-core-java8|1.0.0m1|bundle.

**Pull request closed without merging**
