### PR TITLE
fix typo in documentation

### PR DESCRIPTION
**Pull request by jorgeviana**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks for fixing this ! can you change the corresponding template file too (https://github.com/joel-costigliola/assertj/blob/gh-pages/templates/assertj-core-custom-assertions-template.html) since it is used to generate assertj-core-custom-assertions.html. Thanks!

**Comment by jorgeviana** [comment]
No problem, I didn't understood well the contribution notes. Let me know if the commits are ok.

**Comment by jorgeviana** [comment]
Even simple contributions should not be made at night when one is tired... I think I nailed it this time :)

**Comment by joel-costigliola** [comment]
Looks good thanks! 
We are moving the site/documentation to asciidoc which will make it easier to contribute, it's here and a wip: https://assertj.github.io/doc/

**Pull request merged**
