### PR TITLE
fixed small errors

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
@0xflotus thanks! The thing is this is not the official site anymore, the new one is https://github.com/assertj/doc, could you do the same check for it ? the repo is https://github.com/assertj/doc

**Comment by 0xflotus** [comment]
> @0xflotus thanks! The thing is this is not the official site anymore, the new one is https://github.com/assertj/doc, could you do the same check for it ? the repo is https://github.com/assertj/doc

Done with https://github.com/assertj/doc/pull/9 :)

**Comment by joel-costigliola** [comment]
Closing it as we don't maintain the old site

**Comment by fbiville** [comment]
@joel-costigliola what about updating the README to point to the new repo and archiving this repo (see admin section)? Just my 2 cents :)

**Comment by joel-costigliola** [comment]
@fbiville good point for the README.md but if I archive the repo, would the site go offline ? I'd like to keep it a bit more as it contains information not yet migrated to the new site.

**Pull request closed without merging**
