### PR TITLE
Fixing inconsistent prose / example code

### PR DESCRIPTION
**Pull request by mwatts15**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks for reporting this !

**Comment by croesch** [comment]
Thanks!

**Comment by joel-costigliola** [comment]
@croesch I think you should update `assertj-swing-lookup-template.html` otherwise at the next site generation the changes will be lost.

**Comment by croesch** [comment]
Thanks for fixing @joel-costigliola and @mwatts15

**Pull request merged**
