### PR TITLE
Swing module

### PR DESCRIPTION
**Pull request by croesch**
Hey Joel,

I couldn't help doing it.. I had a look at the website and added a small stub for the swing module.

You said you would like to add a contribution guide first. I hope I don't upset you when I begin editing without the guide..

Actually it feels quite simple and I also added an entry to the news section mentioning that we're working on a Swing module.

Do you manually edit the css files after creating them? Cause they had at least whitespace changes after I created them. That was the only thing being a bit confusing :-)

Best wishes :)

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Hey Christian,

I just finished the doc to edit AssertJ site, it' here : http://joel-costigliola.github.io/assertj/assertj-help.html

I haven't look at what you have done but note that css files are generated from LESS files, you need python and less to be installed.

**Comment by croesch** [comment]
Okay. Great thanks :+1: 

Yes, I've seen that and python + less is installed. Also I had to install lessc. But the output is different to the files checked in. My files did contain line breaks. I can do the generation again and have a deeper look at the diff.

**Comment by croesch** [comment]
Here I committed the diff. So you can have a look at it, too.

[ba01848527e7c082ed79185f4e6c2e76954c12fa](https://github.com/croesch/assertj/commit/ba01848527e7c082ed79185f4e6c2e76954c12fa)

**Comment by croesch** [comment]
I just finished to import everything from [codehaus](http://docs.codehaus.org/display/FEST).

IMO this should be merged before you edit anything else :)

**Comment by joel-costigliola** [comment]
rebased, thanks, that was a lot of work

**Pull request closed without merging**
